# MKID Durham Group Configuration File

title: "MKID Durham Group"
author: "Microwave Kinetic Inductance Detector Group, Durham University"
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap



navbar-links:
  Home: "/"
  MKIDs: "mkids"
  LAB: "lab"
  PROJECTS:
    - "KIDSpec": "projects/kidspec"
    - "MKID CGI": "projects/mkid_cgi"
    - "MKID Microscopy": "projects/microscopy"
    - "POPY": "projects/popy"
    - "READOUT": "projects/readout"
    - "SUPERSMART": "projects/supersmart"
  PEOPLE:
    - "Group Leader": "members/people/leader"
    - "Postdocs": "members/people/postdocs"
    - "PhD Students": "members/people/phd"
    - "Opportunities": "members/people/opportunities"
  NEWS: "news"
  CONTACT: "contact"


title-img: "/assets/img/mkid_logo.png"

social-network-links:
  email: "mkidgroup@durham.ac.uk"
  github: "Durham-MKID"
  youtube: /channel/UCb9MOi4lcNntMLo15oG8Z7A
  google-scholar: citations?user=iHJKYjIAAAAJ&hl=en

rss-description: RSS feed for MKID Durham Group
url-pretty: "mkid-durham.github.io"

share-links-active:
  twitter: true
  linkedin: true
  facebook: false

keywords: "MKID, spectroscopy, Durham, CfAI, detector, KIDSpec, superconducting, astronomy"

navbar-col: "#F3F4F6"
navbar-text-col: "#202020"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#1A1A1A"
link-col: "#0047AB"
hover-col: "#003B8E"
footer-col: "#F3F4F6"
footer-text-col: "#555555"
footer-link-col: "#0047AB"
footer-hover-col: "#003B8E"

date_format: "%B %-d, %Y"
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
